'use client'

import { useState, useEffect } from 'react'
import { fetchAIPosts } from '@/lib/supabase'
import type { AIPost } from '@/lib/supabase'
import { formatDistanceToNow, format } from 'date-fns'
import { PageHeader } from '@/components/organisms/PageHeader'
import ReactMarkdown from 'react-markdown'

export default function AIIntelligencePage() {
  const [posts, setPosts] = useState<AIPost[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchAIPosts(20).then(data => {
      setPosts(data)
      setLoading(false)
    })
  }, [])

  if (loading) {
    return <div className="page-container animate-fade-up" style={{ padding: '2rem', color: 'var(--text-muted)' }}>Loading intelligence briefs...</div>
  }

  return (
    <div className="page-container animate-fade-up">
      <PageHeader
        label="Autonomous Analysis"
        title="Agent Insights"
        subtitle="Automated briefings and drafts generated by the parliamentary monitoring agent."
        meta={format(new Date(), 'EEEE, MMMM do, yyyy')}
      />

      {posts.length === 0 ? (
        <div className="ledger-container" style={{ marginTop: '2.5rem', background: 'var(--surface-1)', border: '1px dashed var(--border)', borderRadius: '12px', padding: '3rem 1.75rem', textAlign: 'center' }}>
          <div style={{ fontSize: '2rem', marginBottom: '1rem' }}>🤖</div>
          <h3 className="heading-md" style={{ color: 'var(--text)', marginBottom: '0.5rem' }}>No AI briefs scheduled</h3>
          <p className="text-muted" style={{ fontSize: '0.875rem' }}>The autonomous agent hasn't generated any new accountability drafts yet.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', marginTop: '2rem' }}>
          {posts.map(post => {
            let mainContent = post.content
            let nepaliSummary = ""
            
            if (mainContent.includes('**Nepali संक्षेप**')) {
               const parts = mainContent.split('**Nepali संक्षेप**')
               mainContent = parts[0].trim()
               nepaliSummary = parts[1].trim()
            } else if (mainContent.includes('**नेपाली संक्षेप**')) {
               const parts = mainContent.split('**नेपाली संक्षेप**')
               mainContent = parts[0].trim()
               nepaliSummary = parts[1].trim()
            }

            return (
              <div key={post.id} style={{ padding: '1.75rem', background: 'var(--surface-1)', borderRadius: '12px', border: '1px solid var(--border)', borderLeft: '4px solid var(--rsp)', position: 'relative' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem', gap: '1rem' }}>
                  <h4 style={{ fontSize: '1.25rem', fontWeight: 600, color: 'var(--text)', margin: 0, lineHeight: 1.3 }}>{post.title.replace(/[\*#]/g, '')}</h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', background: 'var(--surface-2)', padding: '0.25rem 0.5rem', borderRadius: '4px', flexShrink: 0 }}>
                    {formatDistanceToNow(new Date(post.created_at), { addSuffix: true })}
                  </span>
                </div>
                
                <div className="markdown-content" style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: '1.7' }}>
                  <ReactMarkdown>{mainContent}</ReactMarkdown>
                </div>

                {nepaliSummary && (
                  <div className="markdown-content" style={{ marginTop: '1.5rem', paddingTop: '1.5rem', borderTop: '1px dashed var(--border)', fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: '1.7' }}>
                    <span style={{ fontWeight: 600, color: 'var(--text)', display: 'block', marginBottom: '0.75rem' }}>नेपाली संक्षेप</span>
                    <ReactMarkdown>{nepaliSummary}</ReactMarkdown>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
